"use client"

import * as React from "react"
import { toast } from "sonner"
import { BellRing, TriangleAlert } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { EmptyState } from "@/components/ui/empty-state"
import { Skeleton } from "@/components/ui/skeleton"
import {
  fetchNotifications,
  markAllNotificationsRead,
  setNotificationRead,
  type ApiNotification,
} from "@/lib/api-client/notifications"
import { ApiRequestError } from "@/lib/api-client/fetcher"

function formatWhen(iso: string) {
  return new Date(iso).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  })
}

function typeLabel(type: string) {
  const text = type.replace(/[_-]+/g, " ").trim()
  return text.charAt(0).toUpperCase() + text.slice(1)
}

/**
 * "Your Notifications" — the signed-in customer's real notifications (generated by the backend on order
 * and other events), with the real unread count and the read/unread actions the API supports.
 */
function NotificationsListCard() {
  const [items, setItems] = React.useState<ApiNotification[] | null>(null)
  const [unreadCount, setUnreadCount] = React.useState(0)
  const [error, setError] = React.useState<string | null>(null)
  const [reloadToken, setReloadToken] = React.useState(0)
  const [busyId, setBusyId] = React.useState<string | null>(null)
  const [isMarkingAll, setIsMarkingAll] = React.useState(false)

  React.useEffect(() => {
    let cancelled = false

    async function load() {
      try {
        const result = await fetchNotifications()
        if (cancelled) return
        setItems(result.items)
        setUnreadCount(result.unreadCount)
        setError(null)
      } catch (err) {
        if (cancelled) return
        setItems(null)
        setError(
          err instanceof ApiRequestError && err.status === 401
            ? "Please sign in again to see your notifications."
            : "Couldn't load your notifications right now."
        )
      }
    }

    void load()
    return () => {
      cancelled = true
    }
  }, [reloadToken])

  const reload = () => setReloadToken((n) => n + 1)

  async function handleToggle(notification: ApiNotification) {
    setBusyId(notification._id)
    try {
      await setNotificationRead(notification._id, !notification.isRead)
    } catch {
      toast.error("Couldn't update that notification. Please try again.")
    } finally {
      setBusyId(null)
      reload()
    }
  }

  async function handleMarkAll() {
    setIsMarkingAll(true)
    try {
      await markAllNotificationsRead()
      toast.success("All notifications marked as read")
    } catch {
      toast.error("Couldn't mark notifications as read. Please try again.")
    } finally {
      setIsMarkingAll(false)
      reload()
    }
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <CardTitle className="text-h3">Your Notifications</CardTitle>
          {unreadCount > 0 ? <Badge>{unreadCount} unread</Badge> : null}
        </div>
        {unreadCount > 0 ? (
          <Button variant="outline" size="sm" onClick={() => void handleMarkAll()} disabled={isMarkingAll}>
            {isMarkingAll ? "Marking..." : "Mark all as read"}
          </Button>
        ) : null}
      </CardHeader>
      <CardContent>
        {error ? (
          <EmptyState
            icon={TriangleAlert}
            title="Couldn't load notifications"
            description={error}
            action={
              <Button variant="outline" onClick={reload}>
                Try again
              </Button>
            }
          />
        ) : items === null ? (
          <div className="flex flex-col gap-3">
            <Skeleton className="h-4 w-1/3" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-2/3" />
          </div>
        ) : items.length === 0 ? (
          <EmptyState
            icon={BellRing}
            title="You're all caught up"
            description="Order updates and other activity will show up here."
          />
        ) : (
          <ul className="flex flex-col divide-y divide-border">
            {items.map((notification) => (
              <li key={notification._id} className="flex items-start justify-between gap-4 py-3.5 first:pt-0 last:pb-0">
                <div className="flex min-w-0 items-start gap-3">
                  <span
                    aria-label={notification.isRead ? "Read" : "Unread"}
                    className={
                      "mt-1.5 size-2 shrink-0 rounded-full " + (notification.isRead ? "bg-border" : "bg-primary")
                    }
                  />
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <p
                        className={
                          "text-small text-foreground " + (notification.isRead ? "font-medium" : "font-semibold")
                        }
                      >
                        {notification.title}
                      </p>
                      <Badge variant="outline" className="text-muted-foreground">
                        {typeLabel(notification.type)}
                      </Badge>
                    </div>
                    <p className="text-caption text-muted-foreground">{notification.message}</p>
                    <p className="text-caption text-muted-foreground">{formatWhen(notification.sentAt)}</p>
                  </div>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  className="shrink-0"
                  disabled={busyId === notification._id}
                  onClick={() => void handleToggle(notification)}
                >
                  {notification.isRead ? "Mark unread" : "Mark read"}
                </Button>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  )
}

export { NotificationsListCard }
